/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'manolo' at '9/12/16 8:52' with Gradle 3.2.1
 *
 * @author manolo, @date 9/12/16 8:52
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
